AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: GraphQL
Resources:
  GraphQL:
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        EntryPoints:
        - src/index.ts
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs16.x
      Handler: src/index.handler
      CodeUri: ./js-graphql
      PackageType: Zip
      Events:
        GraphQLApi:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY
      Environment:
        Variables:
          DB_URL: 'neo4j+s://c0fa2486.databases.neo4j.io'
          DB_USER: 'neo4j'
          DB_PASSWORD: 'HduRGaPgz92Dl1fpjZ61ovqLKVGq5jEr-MCjbw2Ee4U'
          SALT_ROUND: 1
          SECRET: 'CSCI3100'
  GraphQLIntegration:
    Properties:
      ApiId: !Ref HttpApiGateway
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GraphQL.Arn}/invocations'
      PayloadFormatVersion: '2.0'
    Type: AWS::ApiGatewayV2::Integration
  GraphQLInvokePermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt 'GraphQL.Arn'
      Principal: apigateway.amazonaws.com
    Type: AWS::Lambda::Permission
  GraphQLRoute:
    Properties:
      ApiId: !Ref HttpApiGateway
      AuthorizationType: NONE
      RouteKey: 'ANY /graphql'
      Target: !Sub 'integrations/${GraphQLIntegration}'
    Type: AWS::ApiGatewayV2::Route
  HttpApiGateway:
    Properties:
      # DisableExecuteApiEndPoint: true
      Description: 'HTTP Api Gateway for beaconnect'
      Name: beaconnect-http-api-gateway
      ProtocolType: 'HTTP'
    Type: AWS::ApiGatewayV2::Api
  HttpApiGatewayStage:
    Properties:
      ApiId: !Ref HttpApiGateway
      AutoDeploy: true
      Description: 'Auto Deploy stage for beaconnect ApiGateway' 
      StageName: '$default'
    Type: AWS::ApiGatewayV2::Stage
Outputs:
  GraphQLApiEndPoint:
    Description: 'GraphQL API Gateway endpoint'
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/graphql"
  HTTPApiEndPoint:
    Description: 'HTTP API Gateway endpoint'
    Value: !GetAtt HttpApiGateway.ApiEndpoint
